# This workflow will build a Java project with Maven and run integration tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven .
# Integration tests are run with preloaded test confluence instance.
# For more information, see: https://developer.atlassian.com/server/framework/atlassian-sdk/create-test-data-and-a-test-fixture .

name: on-push-maven-integration-test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install dependencies
        run: yarn install
        working-directory: ./frontend-react
      - name: Build node packages
        run: yarn build
        working-directory: ./frontend-react
      - name: Cache maven modules
        uses: actions/cache@v2
        env:
          cache-name: cache-maven-modules
        with:
          # maven cache files are stored in `~/.m2` on Linux/macOS
          path: ~/.m2
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Integration Test with Maven
        run: |
          mvn package com.atlassian.maven.plugins:confluence-maven-plugin:8.1.0:integration-test \
          -gs ./settings.xml -Dhttp.port='1991' \
          -Dtest.integration.path=./src/test/resources/generated-test-resources.zip  --file ./pom.xml
        working-directory: ./backend

        # This may throw some null pointer exceptions when confluence shuts down and Tomcat stops.
        # Error logs on confluence shut down has been a known issue.
        # For more information, see: https://jira.atlassian.com/browse/CONFSERVER-22879 .
